# Importing useful libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Uploading data from local file directory

In [2]:
# from url 
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv'
# data = pd.read_csv(url)

In [3]:
data = pd.read_csv('energydata_complete.csv')
data.head(2)

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.7900,19.79,44.73,19.0,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.7225,19.79,44.79,19.0,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195

In [4]:
data.drop(['date', 'lights'], axis=1, inplace=True)
data.head(2)

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.7900,19.79,44.73,19.0,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.7225,19.79,44.79,19.0,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195

In [5]:
# Importing neccesary packages

In [6]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [7]:
normalised_data = pd.DataFrame(MinMaxScaler().fit_transform(data), columns=data.columns)
df = normalised_data
df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

# Question 12

In [8]:
X = df['T2'].values.reshape(-1, 1)
y = df['T6']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)
round(lr.score(X_test, y_test), 2)

0.64

In [10]:
y_pred = lr.predict(X_test)
round(r2_score(y_test, y_pred), 2)

0.64

# Question 13

In [11]:
X = df.drop('Appliances', axis=1)
y = df['Appliances']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)
lr = LinearRegression()
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)

In [13]:
round(mae, 2)

0.05

# Question 14

In [14]:
rss = np.sum(np.square(y_test - y_pred))
round(rss, 2)

45.35

# Question 15

In [15]:
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred))
round(rmse_lr, 3)

0.088

# Question 16

In [16]:
r2 = r2_score(y_test, y_pred)
round(r2, 2)

0.15

# Question 17

In [17]:
X = df.drop('Appliances', axis=1)
y = df['Appliances']
X.head()

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [18]:
LinearReg = pd.DataFrame(lr.coef_, index=X.columns, columns=['LinearReg weights'])
LinearReg.sort_values(by='LinearReg weights').drop(['rv1', 'rv2'], axis=0)

             LinearReg weights
RH_2                 -0.456701
T_out                -0.321868
T2                   -0.236185
T9                   -0.189932
RH_8                 -0.157597
RH_out               -0.077681
RH_7                 -0.044613
RH_9                 -0.039795
T5                   -0.015658
T1                   -0.003281
Press_mm_hg           0.006839
T7                    0.010302
Visibility            0.012308
RH_5                  0.016009
RH_4                  0.026388
T4                    0.028984
Windspeed             0.029183
RH_6                  0.038049
RH_3                  0.096045
T8                    0.102000
Tdewpoint             0.117764
T6                    0.236424
T3                    0.290633
RH_1                  0.553546

In [19]:
X = df.drop('Appliances', axis=1)
y = df['Appliances']
X.head()

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

# Question 13

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)
rr = Ridge(alpha=0.4)
rr.fit(X_train, y_train)

y = rr.predict(X_test)
rmse_rr = np.sqrt(mean_squared_error(y_test, y_pred))
round(rmse_rr, 3)

0.088

In [21]:
assert round(rmse_rr, 3) == round(rmse_lr, 3)

In [22]:
X = df.drop('Appliances', axis=1)
y = df['Appliances']

In [23]:
X.head()

,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,RH_5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,0.381691,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,0.381691,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,0.380037,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,0.380037,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,0.380037,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=42)

ls = Lasso(alpha=0.001)
ls.fit(X_train, y_train)

Lasso(alpha=0.001)

# Question 19

In [25]:
LassoReg = pd.DataFrame(ls.coef_, index=X.columns, columns=['LassoReg weights'])
print(f"The number of non zero weights are: {len(LassoReg[LassoReg['LassoReg weights']!=0])}")
LassoReg[LassoReg['LassoReg weights']!=0]

The number of non zero weights are: 4

           LassoReg weights
RH_1               0.017880
RH_8              -0.000110
RH_out            -0.049557
Windspeed          0.002912

# Question 20

In [26]:
y = ls.predict(X_test)
rmse_ls = np.sqrt(mean_squared_error(y_test, y_pred))
round(rmse_ls, 3)

0.088